# Default values for cava-realtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: cava-realtime
# fullnameOverride: cava-realtime
path: /realtime
development: false
service:
  targetPort: 80
  portName: http
  type: ClusterIP
  port: 80
  containerPort: 80
  servicePortName: http
image:
  repository: cormorack/cr-server
  tag: "set-by-chartpress"
  pullSecrets: []
  pullPolicy: Always
replicas: 1
resources: {}
env: []
restartPolicy: Always
nodeSelector: {}
ingress:
  expose: false

  # If secure, must provide tls
  secure: false

  # host: "test.example.com"
  host: ""

  # Adds tls for domain certification
  # Certificate must be created ahead of time
  # tls:
  #   secretName: cava-realtime-cert
  tls: {}

# Kafka Connection details for producer and server
kafkaHost: ""
kafkaPort: ""

# CAVA Producer
producer:
  enabled: true
  nodeSelector: {}
  image:
    repository: cormorack/cr-producer
    tag: "set-by-chartpress"
    pullSecrets: []
    pullPolicy: Always
  restartPolicy: Always
  env:
    - name: CR_PRODUCER_OOI_USERNAME
      value: ""
    - name: CR_PRODUCER_OOI_TOKEN
      value: ""
  resources: {}

kafka:
  enabled: true
  maxMessageBytes: "2000000"
  logRetentionHours: "1"
  logRetentionBytes: "-1"
  logRetentionCheckIntervalMs: "5000"
  extraEnvVars:
    - name: KAFKA_CFG_OFFSETS_RETENTION_MINUTES
      value: "2"
    - name: KAFKA_CFG_LOG_CLEANUP_POLICY
      value: "delete"
    - name: KAFKA_CFG_LOG_RETENTION_MS
      value: "900000" # 15 minutes
    - name: KAFKA_CFG_LOG_ROLL_MS
      value: "900000" # 15 minutes
    - name: KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS
      value: "1"
  zookeeper:
    enabled: true
