
title: Interactive Oceans Data Service Helm charts for Kubernetes
description: This site stores Helm chart tarballs for Interactive Oceans Realtime Service.
theme: minima
url: "https://cormorack.github.io/cava-realtime/"
repo_name: cava-realtime

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
