ARG CONDA_VERSION=4.9.2
ARG PYTHON_VERSION=3.7

FROM cormorack/uvicorn-gunicorn:python${PYTHON_VERSION}-conda${CONDA_VERSION}
COPY ./cava_realtime/application /app
RUN which pip && pip install -e /tmp