version: "3.2"

services:
    zookeeper:
        image: bitnami/zookeeper:3.6.3
        environment:
          ALLOW_ANONYMOUS_LOGIN: "yes"
        ports:
          - 2181:2181
        networks:
          - io2network
    kafka:
        image: bitnami/kafka:2.8.0
        environment:
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_MESSAGE_MAX_BYTES=2000000
            - KAFKA_CFG_LOG_RETENTION_HOURS=1
            # IDK what the flag for fetch.message.max.bytes is on here
            # (might need to copy the configfile over to the Kafka container)
        ports:
            - 9092:9092
            - 29092:29092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - zookeeper
        depends_on:
            - zookeeper
        networks:
            - io2network

networks:
    io2network: