version: "3.2"

services:
    cr-producer:
        build:
            context: ../../src/cava_realtime
            dockerfile: ../../resources/docker/producer.dockerfile
        image: cormorack/cr-producer:latest
        environment:
            - CR_PRODUCER_OOI_USERNAME=${OOI_USERNAME}
            - CR_PRODUCER_OOI_TOKEN=${OOI_TOKEN}
            - CR_PRODUCER_KAFKA_HOST=kafka
            - CR_PRODUCER_KAFKA_PORT=29092
        depends_on:
            - kafka
        networks:
            - io2network
    cr-server:
        build:
            context: ../../src/cava_realtime/application
            dockerfile: ../../../resources/docker/Dockerfile
        image: cormorack/cr-server:latest
        ports:
            - 8080:80
        environment:
            - CR_API_KAFKA_HOST=kafka
            - CR_API_KAFKA_PORT=29092
        depends_on:
            - kafka
        networks:
            - io2network
    zookeeper:
        image: bitnami/zookeeper:3.6.3
        environment:
          ALLOW_ANONYMOUS_LOGIN: "yes"
        ports:
          - 2181:2181
        networks:
          - io2network
    kafka:
        image: bitnami/kafka:2.8.0
        environment:
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
            # - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://:29092
            # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_MESSAGE_MAX_BYTES=2000000
            #- KAFKA_CFG_LOG_RETENTION_HOURS=1
            - KAFKA_CFG_OFFSETS_RETENTION_MINUTES=2
            - KAFKA_CFG_LOG_RETENTION_MINUTES=1
            # - HOSTNAME=kafka
            # IDK what the flag for fetch.message.max.bytes is on here
            # (might need to copy the configfile over to the Kafka container)
        ports:
            - 9092:9092
            - 29092:29092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - zookeeper
        depends_on:
            - zookeeper
        networks:
            - io2network
    kafka-kv:
        image: kafka-kv:latest
        ports:
          - 8081:8081
        # extra_hosts:
        #     - "host.docker.internal:host-gateway"
        links:
          - kafka
        depends_on:
          - kafka
        command:
          - --topic
          - RS03AXPS-SF03A-2A-CTDPFA302-streamed-ctdpf_sbe43_sample__raw
          - --streams-props
          - bootstrap.servers=kafka:29092
          - num.standby.replicas=1
          - --application-id
          - my-streams-processor
          - --hostname
          - localhost
        networks:
            - io2network

networks:
    io2network: