name: Cava realtime PR Build

on:
  pull_request:
    paths-ignore:
      - README.md
      - "resources/helm/**"
      - "**/test-chart.yml"
      - ".ci-helpers/**"

env:
  DOCKER_ORG: cormorack
  CONDA_VERSION: 4.9.2
  PYTHON_VERSION: 3.7

jobs:
  producer-docker-build:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: cr-producer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          DOCKER_TAG=PR
          IMAGE_SPEC="${DOCKER_ORG}/${{ env.IMAGE_NAME }}:${DOCKER_TAG}"
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src/cava_realtime
          file: ./resources/docker/producer.dockerfile
          push: false
          build-args: |
            CONDA_VERSION=${{ env.CONDA_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          tags: |
            ${{ env.IMAGE_SPEC }}
  server-docker-build:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: cr-server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          DOCKER_TAG=PR
          IMAGE_SPEC="${DOCKER_ORG}/${{ env.IMAGE_NAME }}:${DOCKER_TAG}"
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src/cava_realtime
          file: ./resources/docker/producer.dockerfile
          push: false
          build-args: |
            CONDA_VERSION=${{ env.CONDA_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          tags: |
            ${{ env.IMAGE_SPEC }}